In [2]:
import numpy as np


## creating arrya from list

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array: ",arr_2d)

1D array:  [1 2 3 4 5]
2d array:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [9]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

np_array = np.array([1,2,3]) #element wise multiplication
print("python array multiplication", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)


start = time.time()
np_array = np.arange(1000000)*2
print("\n List operation time: ", time.time()-start)


python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List operation time:  0.1215829849243164

 List operation time:  0.0028204917907714844


# creating array form scratch

In [8]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

oness = np.ones((2,3))
print("ones array: \n",oness)

print(oness.dtype)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
float64


In [5]:
full = np.full((2,3),7)
print("full array: \n",full)


full array: 
 [[7 7 7]
 [7 7 7]]


In [13]:
random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequences array: \n",sequence)

random array: 
 [[0.60830867 0.52952633 0.0171182 ]
 [0.81275167 0.43086134 0.13962534]]
sequences array: 
 [0 2 4 6 8]


# vector, matrix and tensor

In [7]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix:",matrix)


tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:",tensor)


Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties 


In [4]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("ARRAY: ",arr)

ARRAY:  [[1 2 3]
 [4 5 6]]
