In [1]:
import numpy as np

## creating array from list

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array: ",arr_2d)

1D array:  [1 2 3 4 5]
2d array:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [7]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

np_array = np.array([1,2,3]) #element wise multiplication
print("python array multiplication", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)


start = time.time()
np_array = np.arange(1000000)*2
print("\n List operation time: ", time.time()-start)


python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List operation time:  0.11096310615539551

 List operation time:  0.009973764419555664


# creating array form scratch

In [8]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

oness = np.ones((2,3))
print("ones array: \n",oness)

print(oness.dtype)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
float64


In [9]:
full = np.full((2,3),7)
print("full array: \n",full)


full array: 
 [[7 7 7]
 [7 7 7]]


In [10]:
random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequences array: \n",sequence)

random array: 
 [[0.55160436 0.02999939 0.44225594]
 [0.64928897 0.39262228 0.99863446]]
sequences array: 
 [0 2 4 6 8]


# vector, matrix and tensor

In [11]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix:",matrix)


tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:",tensor)


Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties 


In [2]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("dtye",arr.dtype)



Shape  (2, 3)
Dimension 2
Size 6
dtye int64


##### numpy arrays m always similar data hi use kiya jata h  , or yehi reason h ki numpy m arrays optimised rehti h 

## array reshaping


In [14]:
arr = np.arange(12)
print("original array", arr)

reshaped = arr.reshape((3,4))
print("\n \n Reshaped array", reshaped)

# flatten (copy of original array , agr flatten perform krne ke bad kuch bhi krta hu array m jo muje flatten se mili h to original m kuch bhi chnges nhi honge!!)
flattened = reshaped.flatten()
print("\nflattened array", flattened)

# ravel (returns view , insted of copy , share same memory of original array so, chnges in array got after ravel , make chnges in original array!!)
raveled = reshaped.ravel()
print("raveled array", raveled)



original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 
 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


# Transpose of array (matrices)

In [16]:
arr = np.arange(12)
print("original array", arr)

reshaped = arr.reshape((3,4))
print("\n \n Reshaped array", reshaped)

# studied in maths............
transpose = reshaped.T
print("\n Transpose array", transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 
 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
